// Descarga la transcripción pública (subtítulos automáticos u oficiales) de un
// video de YouTube usando el mismo mecanismo no documentado que usan
// extensiones/herramientas gratuitas de "YouTube transcript". No es una API
// oficial: puede fallar o dejar de funcionar sin aviso. Corre en Node (no en
// el navegador) para evitar el bloqueo de CORS que tendría en un sitio web.

const WATCH_URL = "https://www.youtube.com/watch?v=";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

function decodeHtmlEntities(str) {
  return str
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'");
}

function pickTrack(tracks, preferredLangs) {
  for (const lang of preferredLangs) {
    const exact = tracks.find((t) => t.languageCode === lang);
    if (exact) return exact;
  }
  return tracks[0];
}

/**
 * @param {string} videoId
 * @param {string[]} preferredLangs
 * @returns {Promise<{ text: string, hook: string, language: string, isAutoGenerated: boolean } | null>}
 */
export async function fetchTranscript(videoId, preferredLangs = ["es", "en"]) {
  try {
    const pageRes = await fetch(`${WATCH_URL}${videoId}`, {
      headers: { "User-Agent": UA, "Accept-Language": "es,en;q=0.8" },
    });
    if (!pageRes.ok) return null;
    const html = await pageRes.text();

    const match = html.match(/"captionTracks":(\[.*?\])(?=,")/s);
    if (!match) return null;

    const tracks = JSON.parse(match[1]);
    if (!tracks.length) return null;

    const track = pickTrack(tracks, preferredLangs);
    const transcriptRes = await fetch(track.baseUrl, { headers: { "User-Agent": UA } });
    if (!transcriptRes.ok) return null;
    const xml = await transcriptRes.text();

    const lines = [...xml.matchAll(/<text[^>]*>([\s\S]*?)<\/text>/g)].map((m) =>
      decodeHtmlEntities(m[1].replace(/<[^>]+>/g, "")).trim()
    );
    const text = lines.join(" ").replace(/\s+/g, " ").trim();
    if (!text) return null;

    return {
      text,
      hook: lines.slice(0, 4).join(" ").replace(/\s+/g, " ").trim(),
      language: track.languageCode,
      isAutoGenerated: track.kind === "asr",
    };
  } catch {
    return null;
  }
}
