// Transcripción de Buzz — "5 alimentos que sí + 5 que dejar atrás (después de los 60)".
// Voz del usuario: public/audio/health-narration.mp3
export interface Cue {i: number; start: number; end: number; text: string;}

export const cues: Cue[] = [
  {i: 1, start: 0, end: 5.38, text: "Hay algo que note con los años y quizás a ti te pas igual. Después de los 60, el cuerpo"},
  {i: 2, start: 5.38, end: 10.7, text: "ya no responde igual a lo que comemos. Hay comidas que te dejan con energía toda la tarde"},
  {i: 3, start: 10.7, end: 16.58, text: "y otras, sin darte cuenta, te están dejando pesado, cansado y sin ganas. Hoy te voy a"},
  {i: 4, start: 16.58, end: 22.74, text: "compartir 5 alimentos que a muchos nos sientan de maravilla después de los 60 y 5 que quizás"},
  {i: 5, start: 22.74, end: 27.58, text: "valga la pena dejar en el pasado, no como una real estricta, sino como una charla entre"},
  {i: 6, start: 27.58, end: 33.1, text: "nosotros. Así que quédate que el número 3 es de los que sorprende a mucha gente."},
  {i: 7, start: 33.1, end: 37.3, text: "Y quiero decirte algo antes de empezar. Yo no soy médico ni vengo a darte lo que tienes"},
  {i: 8, start: 37.3, end: 41.98, text: "que hacer. Esto es simplemente lo que la experiencia y el sentido común nos han enseñado sobre"},
  {i: 9, start: 41.98, end: 46.96, text: "comer para sentirnos mejor. Tú conoces tu cuerpo mejor que nadie, así que toma lo que"},
  {i: 10, start: 46.96, end: 52.14, text: "te sirva y lo demás déjalo pasar. ¿Te parece? Pues empecemos por lo bueno."},
  {i: 11, start: 52.14, end: 56.3, text: "La avena. Un plato de avena en la mañana es de las cosas más sencillas que rinden todo"},
  {i: 12, start: 56.3, end: 61.16, text: "el día. Es suave con el estómago, te llena sin pesarte y puedes combinarlo con lo que"},
  {i: 13, start: 61.16, end: 67.38, text: "quieras. Una fruta, un poco de canela, unas nueces, muchos me dicen que desde que la incorporaron"},
  {i: 14, start: 67.38, end: 70.58, text: "guían a media mañana sin ese bajón de energía."},
  {i: 15, start: 70.58, end: 76.46, text: "Número 2 Las legumbres. Lentejas, carbanzos, frijoles, lo que comían nuestros abuelos"},
  {i: 16, start: 76.46, end: 82.46, text: "y no por casualidad. Son económicas, rinden y te dejan satisfecho. Un buen plato de lentejas"},
  {i: 17, start: 82.46, end: 87.3, text: "un par de veces por semana es de esas costumbres que nunca pasan de moda."},
  {i: 18, start: 87.3, end: 92.02, text: "Número 3 El pescado. Aquí es tal que te dije, el pescado sobre todo del azul como"},
  {i: 19, start: 92.02, end: 97.22, text: "salmón, sardina, es de esos alimentos que le caen bien al cuerpo con los años. Y no"},
  {i: 20, start: 97.22, end: 102.54, text: "tiene que ser caro, una lata de sardinas buena es tan valiosa como un filete. Suave,"},
  {i: 21, start: 102.54, end: 105.3, text: "fácil de preparar y muy agradecido."},
  {i: 22, start: 105.3, end: 111.54, text: "Número 4 Las verduras de oja verde. Espinaca, acelga, lechuga, por le colorar platos. No"},
  {i: 23, start: 111.58, end: 116.98, text: "hace falta volverte experto en ensaladas raras. Una porción de verdura verde al día, cocida,"},
  {i: 24, start: 116.98, end: 120.82, text: "o cruda, como más te guste, le da frescura cualquier comida."},
  {i: 25, start: 120.82, end: 126.78, text: "Número 5 El yogur natural. Y para cerrar algo sencillo, un yogur natural sin tantos"},
  {i: 26, start: 126.78, end: 132.46, text: "azucar añadidos es suave, refrescante y a mucha gente le sienta bien en la digestión."},
  {i: 27, start: 132.46, end: 136.3, text: "Un buen tentempí de media tarde con una fruta y listo."},
  {i: 28, start: 136.3, end: 141.5, text: "Y ahora a la otra parte. Y ojo, no te voy a decir que esto es veneno, nada de dramas,"},
  {i: 29, start: 141.5, end: 145.3, text: "solo son cosas que con los años muchos notamos que ya nos sientan igual."},
  {i: 30, start: 145.3, end: 151.18, text: "Número 1 Los embutidos y las carnes procesadas. El jamón muy procesado, las salchichas,"},
  {i: 31, start: 151.18, end: 156.3, text: "esas cosas prácticas pero llenas de sal, de vez en cuando no pasa nada, pero como"},
  {i: 32, start: 156.3, end: 159.3, text: "costumbre diaria, muchos sienten que les cae pesado."},
  {i: 33, start: 159.3, end: 166.1, text: "Número 2 Las bebidas azucaradas. Los refrescos y jugos muy dulces dan un subidón rápido."},
  {i: 34, start: 166.1, end: 172.54, text: "Y luego el bajón. El agua natural, un té, una infusión, tu cuerpo lo agradece más de lo que crees."},
  {i: 35, start: 172.54, end: 179.34, text: "Número 3 Las frituras muy cargadas. No digo que nunca comas algo frito, un gusto de vez en cuando"},
  {i: 36, start: 179.34, end: 184.34, text: "es parte de la vida, pero de diario, las frituras pesadas le quitan ligerés al día."},
  {i: 37, start: 184.34, end: 190.86, text: "Número 4 La bollería industrial. Esos pastelitos y galletas empaquetadas se ven inofensivos,"},
  {i: 38, start: 190.86, end: 195.82, text: "pero llenan de azúcar sin darte nada de energía real. Un postre casero hecho con calma,"},
  {i: 39, start: 195.82, end: 201.7, text: "siempre será mejor compañía. Número 5 El exceso de sal en general. No la salen sí,"},
  {i: 40, start: 201.7, end: 208.42, text: "sino el exceso. Los snacks alado, los caldos de sobre, con los años, cocinar con hierbas y"},
  {i: 41, start: 208.42, end: 212.54, text: "especias en vez de tanta sal le devuelve el sabor de verdad a la comida."},
  {i: 42, start: 212.54, end: 218.22, text: "Y fíjate en algo, nada de esto es una dieta estricta, es simplemente volver a lo sencillo,"},
  {i: 43, start: 218.22, end: 223.46, text: "a lo de siempre, a lo que nos hace sentir bien. No se trata de prohibirte nada,"},
  {i: 44, start: 223.46, end: 229.1, text: "se trata de escuchar a tu cuerpo y darle la mayor parte del tiempo lo que mantiene con energía"},
  {i: 45, start: 229.1, end: 235.54, text: "y buen ánimo. Empieza por uno solo, mañana, un plato de avena, y viviendo como te sientes."},
  {i: 46, start: 235.54, end: 241.82, text: "Si esta charla te sirvió, suscríbete. Aquí compartimos ideas sencillas para vivir con más"},
  {i: 47, start: 241.82, end: 247.74, text: "energía después de los 50 y los 60 sin complicaciones. Y cuéntame en los comentarios,"},
  {i: 48, start: 247.86, end: 253.54, text: "¿cuál de estos alimentos es tu favorito? ¿Cuál ya dejaste atrás? Me encantaría leerte."},
  {i: 49, start: 253.54, end: 256.78, text: "Cuídate mucho y nos vemos en el próximo vídeo."},
];

export const DURATION_SECONDS = 256.9;
