export type FlagQuestion = {
  flag: string;
  country: string;
  continent: string;
};

export const FLAGS: FlagQuestion[] = [
  { flag: '🇧🇷', country: 'Brazil', continent: 'South America' },
  { flag: '🇯🇵', country: 'Japan', continent: 'Asia' },
  { flag: '🇨🇦', country: 'Canada', continent: 'North America' },
  { flag: '🇦🇺', country: 'Australia', continent: 'Oceania' },
  { flag: '🇲🇽', country: 'Mexico', continent: 'North America' },
  { flag: '🇩🇪', country: 'Germany', continent: 'Europe' },
  { flag: '🇮🇹', country: 'Italy', continent: 'Europe' },
  { flag: '🇰🇷', country: 'South Korea', continent: 'Asia' },
  { flag: '🇦🇷', country: 'Argentina', continent: 'South America' },
  { flag: '🇹🇷', country: 'Turkey', continent: 'Asia/Europe' },
  { flag: '🇪🇬', country: 'Egypt', continent: 'Africa' },
  { flag: '🇸🇪', country: 'Sweden', continent: 'Europe' },
  { flag: '🇳🇴', country: 'Norway', continent: 'Europe' },
  { flag: '🇵🇱', country: 'Poland', continent: 'Europe' },
  { flag: '🇹🇭', country: 'Thailand', continent: 'Asia' },
  { flag: '🇨🇴', country: 'Colombia', continent: 'South America' },
  { flag: '🇳🇬', country: 'Nigeria', continent: 'Africa' },
  { flag: '🇵🇭', country: 'Philippines', continent: 'Asia' },
  { flag: '🇨🇱', country: 'Chile', continent: 'South America' },
  { flag: '🇵🇰', country: 'Pakistan', continent: 'Asia' },
  { flag: '🇮🇪', country: 'Ireland', continent: 'Europe' },
  { flag: '🇨🇭', country: 'Switzerland', continent: 'Europe' },
  { flag: '🇵🇪', country: 'Peru', continent: 'South America' },
  { flag: '🇬🇷', country: 'Greece', continent: 'Europe' },
  { flag: '🇵🇹', country: 'Portugal', continent: 'Europe' },
  { flag: '🇮🇳', country: 'India', continent: 'Asia' },
  { flag: '🇨🇺', country: 'Cuba', continent: 'North America' },
  { flag: '🇿🇦', country: 'South Africa', continent: 'Africa' },
  { flag: '🇫🇮', country: 'Finland', continent: 'Europe' },
  { flag: '🇮🇸', country: 'Iceland', continent: 'Europe' },
  { flag: '🇯🇲', country: 'Jamaica', continent: 'North America' },
  { flag: '🇻🇳', country: 'Vietnam', continent: 'Asia' },
  { flag: '🇲🇦', country: 'Morocco', continent: 'Africa' },
  { flag: '🇭🇷', country: 'Croatia', continent: 'Europe' },
  { flag: '🇳🇿', country: 'New Zealand', continent: 'Oceania' },
  { flag: '🇷🇸', country: 'Serbia', continent: 'Europe' },
  { flag: '🇪🇨', country: 'Ecuador', continent: 'South America' },
  { flag: '🇳🇵', country: 'Nepal', continent: 'Asia' },
  { flag: '🇰🇪', country: 'Kenya', continent: 'Africa' },
  { flag: '🇧🇩', country: 'Bangladesh', continent: 'Asia' },
  { flag: '🇺🇦', country: 'Ukraine', continent: 'Europe' },
  { flag: '🇨🇿', country: 'Czech Republic', continent: 'Europe' },
  { flag: '🇩🇰', country: 'Denmark', continent: 'Europe' },
  { flag: '🇵🇦', country: 'Panama', continent: 'North America' },
  { flag: '🇸🇦', country: 'Saudi Arabia', continent: 'Asia' },
  { flag: '🇮🇩', country: 'Indonesia', continent: 'Asia' },
  { flag: '🇧🇪', country: 'Belgium', continent: 'Europe' },
  { flag: '🇷🇴', country: 'Romania', continent: 'Europe' },
  { flag: '🇭🇺', country: 'Hungary', continent: 'Europe' },
  { flag: '🇧🇴', country: 'Bolivia', continent: 'South America' },
];
