export type FlagQuestion = {
  flag: string;
  country: string;
  continent: string;
  audioFile: string;
};

export const FLAGS: FlagQuestion[] = [
  { flag: '🇧🇷', country: 'Brazil', continent: 'South America', audioFile: 'audio/countries/brazil.mp3' },
  { flag: '🇯🇵', country: 'Japan', continent: 'Asia', audioFile: 'audio/countries/japan.mp3' },
  { flag: '🇨🇦', country: 'Canada', continent: 'North America', audioFile: 'audio/countries/canada.mp3' },
  { flag: '🇦🇺', country: 'Australia', continent: 'Oceania', audioFile: 'audio/countries/australia.mp3' },
  { flag: '🇲🇽', country: 'Mexico', continent: 'North America', audioFile: 'audio/countries/mexico.mp3' },
  { flag: '🇩🇪', country: 'Germany', continent: 'Europe', audioFile: 'audio/countries/germany.mp3' },
  { flag: '🇮🇹', country: 'Italy', continent: 'Europe', audioFile: 'audio/countries/italy.mp3' },
  { flag: '🇰🇷', country: 'South Korea', continent: 'Asia', audioFile: 'audio/countries/south_korea.mp3' },
  { flag: '🇦🇷', country: 'Argentina', continent: 'South America', audioFile: 'audio/countries/argentina.mp3' },
  { flag: '🇹🇷', country: 'Turkey', continent: 'Asia/Europe', audioFile: 'audio/countries/turkey.mp3' },
  { flag: '🇪🇬', country: 'Egypt', continent: 'Africa', audioFile: 'audio/countries/egypt.mp3' },
  { flag: '🇸🇪', country: 'Sweden', continent: 'Europe', audioFile: 'audio/countries/sweden.mp3' },
  { flag: '🇳🇴', country: 'Norway', continent: 'Europe', audioFile: 'audio/countries/norway.mp3' },
  { flag: '🇵🇱', country: 'Poland', continent: 'Europe', audioFile: 'audio/countries/poland.mp3' },
  { flag: '🇹🇭', country: 'Thailand', continent: 'Asia', audioFile: 'audio/countries/thailand.mp3' },
  { flag: '🇨🇴', country: 'Colombia', continent: 'South America', audioFile: 'audio/countries/colombia.mp3' },
  { flag: '🇳🇬', country: 'Nigeria', continent: 'Africa', audioFile: 'audio/countries/nigeria.mp3' },
  { flag: '🇵🇭', country: 'Philippines', continent: 'Asia', audioFile: 'audio/countries/philippines.mp3' },
  { flag: '🇨🇱', country: 'Chile', continent: 'South America', audioFile: 'audio/countries/chile.mp3' },
  { flag: '🇵🇰', country: 'Pakistan', continent: 'Asia', audioFile: 'audio/countries/pakistan.mp3' },
  { flag: '🇮🇪', country: 'Ireland', continent: 'Europe', audioFile: 'audio/countries/ireland.mp3' },
  { flag: '🇨🇭', country: 'Switzerland', continent: 'Europe', audioFile: 'audio/countries/switzerland.mp3' },
  { flag: '🇵🇪', country: 'Peru', continent: 'South America', audioFile: 'audio/countries/peru.mp3' },
  { flag: '🇬🇷', country: 'Greece', continent: 'Europe', audioFile: 'audio/countries/greece.mp3' },
  { flag: '🇵🇹', country: 'Portugal', continent: 'Europe', audioFile: 'audio/countries/portugal.mp3' },
  { flag: '🇮🇳', country: 'India', continent: 'Asia', audioFile: 'audio/countries/india.mp3' },
  { flag: '🇨🇺', country: 'Cuba', continent: 'North America', audioFile: 'audio/countries/cuba.mp3' },
  { flag: '🇿🇦', country: 'South Africa', continent: 'Africa', audioFile: 'audio/countries/south_africa.mp3' },
  { flag: '🇫🇮', country: 'Finland', continent: 'Europe', audioFile: 'audio/countries/finland.mp3' },
  { flag: '🇮🇸', country: 'Iceland', continent: 'Europe', audioFile: 'audio/countries/iceland.mp3' },
  { flag: '🇯🇲', country: 'Jamaica', continent: 'North America', audioFile: 'audio/countries/jamaica.mp3' },
  { flag: '🇻🇳', country: 'Vietnam', continent: 'Asia', audioFile: 'audio/countries/vietnam.mp3' },
  { flag: '🇲🇦', country: 'Morocco', continent: 'Africa', audioFile: 'audio/countries/morocco.mp3' },
  { flag: '🇭🇷', country: 'Croatia', continent: 'Europe', audioFile: 'audio/countries/croatia.mp3' },
  { flag: '🇳🇿', country: 'New Zealand', continent: 'Oceania', audioFile: 'audio/countries/new_zealand.mp3' },
  { flag: '🇷🇸', country: 'Serbia', continent: 'Europe', audioFile: 'audio/countries/serbia.mp3' },
  { flag: '🇪🇨', country: 'Ecuador', continent: 'South America', audioFile: 'audio/countries/ecuador.mp3' },
  { flag: '🇳🇵', country: 'Nepal', continent: 'Asia', audioFile: 'audio/countries/nepal.mp3' },
  { flag: '🇰🇪', country: 'Kenya', continent: 'Africa', audioFile: 'audio/countries/kenya.mp3' },
  { flag: '🇧🇩', country: 'Bangladesh', continent: 'Asia', audioFile: 'audio/countries/bangladesh.mp3' },
  { flag: '🇺🇦', country: 'Ukraine', continent: 'Europe', audioFile: 'audio/countries/ukraine.mp3' },
  { flag: '🇨🇿', country: 'Czech Republic', continent: 'Europe', audioFile: 'audio/countries/czech_republic.mp3' },
  { flag: '🇩🇰', country: 'Denmark', continent: 'Europe', audioFile: 'audio/countries/denmark.mp3' },
  { flag: '🇵🇦', country: 'Panama', continent: 'North America', audioFile: 'audio/countries/panama.mp3' },
  { flag: '🇸🇦', country: 'Saudi Arabia', continent: 'Asia', audioFile: 'audio/countries/saudi_arabia.mp3' },
  { flag: '🇮🇩', country: 'Indonesia', continent: 'Asia', audioFile: 'audio/countries/indonesia.mp3' },
  { flag: '🇧🇪', country: 'Belgium', continent: 'Europe', audioFile: 'audio/countries/belgium.mp3' },
  { flag: '🇷🇴', country: 'Romania', continent: 'Europe', audioFile: 'audio/countries/romania.mp3' },
  { flag: '🇭🇺', country: 'Hungary', continent: 'Europe', audioFile: 'audio/countries/hungary.mp3' },
  { flag: '🇧🇴', country: 'Bolivia', continent: 'South America', audioFile: 'audio/countries/bolivia.mp3' },
];
