import {FlagQuestion} from './flagQuizData';

export const FLAGS_SHORT: FlagQuestion[] = [
  { flag: '🇧🇷', country: 'Brazil', continent: 'South America', audioFile: 'audio/countries/brazil.mp3' },
  { flag: '🇯🇵', country: 'Japan', continent: 'Asia', audioFile: 'audio/countries/japan.mp3' },
  { flag: '🇨🇦', country: 'Canada', continent: 'North America', audioFile: 'audio/countries/canada.mp3' },
  { flag: '🇦🇺', country: 'Australia', continent: 'Oceania', audioFile: 'audio/countries/australia.mp3' },
  { flag: '🇩🇪', country: 'Germany', continent: 'Europe', audioFile: 'audio/countries/germany.mp3' },
  { flag: '🇮🇹', country: 'Italy', continent: 'Europe', audioFile: 'audio/countries/italy.mp3' },
  { flag: '🇰🇷', country: 'South Korea', continent: 'Asia', audioFile: 'audio/countries/south_korea.mp3' },
  { flag: '🇹🇷', country: 'Turkey', continent: 'Asia/Europe', audioFile: 'audio/countries/turkey.mp3' },
  { flag: '🇪🇬', country: 'Egypt', continent: 'Africa', audioFile: 'audio/countries/egypt.mp3' },
  { flag: '🇳🇴', country: 'Norway', continent: 'Europe', audioFile: 'audio/countries/norway.mp3' },
  { flag: '🇹🇭', country: 'Thailand', continent: 'Asia', audioFile: 'audio/countries/thailand.mp3' },
  { flag: '🇳🇬', country: 'Nigeria', continent: 'Africa', audioFile: 'audio/countries/nigeria.mp3' },
  { flag: '🇮🇪', country: 'Ireland', continent: 'Europe', audioFile: 'audio/countries/ireland.mp3' },
  { flag: '🇬🇷', country: 'Greece', continent: 'Europe', audioFile: 'audio/countries/greece.mp3' },
  { flag: '🇮🇳', country: 'India', continent: 'Asia', audioFile: 'audio/countries/india.mp3' },
  { flag: '🇿🇦', country: 'South Africa', continent: 'Africa', audioFile: 'audio/countries/south_africa.mp3' },
  { flag: '🇯🇲', country: 'Jamaica', continent: 'North America', audioFile: 'audio/countries/jamaica.mp3' },
  { flag: '🇻🇳', country: 'Vietnam', continent: 'Asia', audioFile: 'audio/countries/vietnam.mp3' },
  { flag: '🇳🇿', country: 'New Zealand', continent: 'Oceania', audioFile: 'audio/countries/new_zealand.mp3' },
  { flag: '🇳🇵', country: 'Nepal', continent: 'Asia', audioFile: 'audio/countries/nepal.mp3' },
  { flag: '🇺🇦', country: 'Ukraine', continent: 'Europe', audioFile: 'audio/countries/ukraine.mp3' },
  { flag: '🇩🇰', country: 'Denmark', continent: 'Europe', audioFile: 'audio/countries/denmark.mp3' },
  { flag: '🇸🇦', country: 'Saudi Arabia', continent: 'Asia', audioFile: 'audio/countries/saudi_arabia.mp3' },
  { flag: '🇮🇩', country: 'Indonesia', continent: 'Asia', audioFile: 'audio/countries/indonesia.mp3' },
  { flag: '🇭🇺', country: 'Hungary', continent: 'Europe', audioFile: 'audio/countries/hungary.mp3' },
];
