// Cloudflare Worker: proxy gratuito para descargar transcripciones públicas
// de YouTube sin que el navegador choque con CORS. No usa ninguna clave ni
// cuota — solo reenvía la misma técnica no oficial que ya usa
// youtube-research-copilot/scripts/transcript.mjs, pero corriendo en el
// servidor (edge de Cloudflare) en vez del navegador.
//
// Deploy: pega este archivo completo en el editor de Cloudflare Workers
// (dash.cloudflare.com → Workers & Pages → Create → Edit code) y publica.
// Endpoint resultante: https://<tu-worker>.workers.dev/?videoId=XXXXXXXXXXX

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

function decodeHtmlEntities(str) {
  return str
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'");
}

function pickTrack(tracks, preferredLangs) {
  for (const lang of preferredLangs) {
    const exact = tracks.find((t) => t.languageCode === lang);
    if (exact) return exact;
  }
  return tracks[0];
}

async function fetchTranscript(videoId, preferredLangs) {
  const pageRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: { "User-Agent": UA, "Accept-Language": "es,en;q=0.8" },
  });
  if (!pageRes.ok) return null;
  const html = await pageRes.text();

  const match = html.match(/"captionTracks":(\[.*?\])(?=,")/s);
  if (!match) return null;

  const tracks = JSON.parse(match[1]);
  if (!tracks.length) return null;

  const track = pickTrack(tracks, preferredLangs);
  const transcriptRes = await fetch(track.baseUrl, { headers: { "User-Agent": UA } });
  if (!transcriptRes.ok) return null;
  const xml = await transcriptRes.text();

  const lines = [...xml.matchAll(/<text[^>]*>([\s\S]*?)<\/text>/g)].map((m) =>
    decodeHtmlEntities(m[1].replace(/<[^>]+>/g, "")).trim()
  );
  const text = lines.join(" ").replace(/\s+/g, " ").trim();
  if (!text) return null;

  return {
    text,
    hook: lines.slice(0, 4).join(" ").replace(/\s+/g, " ").trim(),
    language: track.languageCode,
    isAutoGenerated: track.kind === "asr",
  };
}

export default {
  async fetch(request) {
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: CORS_HEADERS });
    }

    const url = new URL(request.url);
    const videoId = url.searchParams.get("videoId");
    const langsParam = url.searchParams.get("langs");
    const preferredLangs = langsParam ? langsParam.split(",") : ["es", "en"];

    if (!videoId) {
      return new Response(JSON.stringify({ error: "Falta el parámetro videoId" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...CORS_HEADERS },
      });
    }

    try {
      const transcript = await fetchTranscript(videoId, preferredLangs);
      return new Response(JSON.stringify(transcript ?? null), {
        headers: { "Content-Type": "application/json", ...CORS_HEADERS },
      });
    } catch (err) {
      return new Response(JSON.stringify({ error: err.message }), {
        status: 500,
        headers: { "Content-Type": "application/json", ...CORS_HEADERS },
      });
    }
  },
};
